version: '3.7'

services:
    database:
        image: 'mysql:5.7'
        container_name: symfony-mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        ports:
            - '3306:3306'
        volumes:
            - db-data:/var/lib/mysql

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: symfony-php
        volumes:
            - .:/var/www/html
        depends_on:
            - database
        working_dir: /var/www/html

    nginx:
        image: nginx:alpine
        container_name: symfony-nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

volumes:
    db-data:
